#!/usr/bin/env bash

# Deploy to ssh server
[[ -z "$SSH_HOST" || -z "$SSH_DIR" ]] && {
    echo "Missing SSH_HOST ($SSH_HOST) or SSH_DIR ($SSH_DIR)."
    exit 1
}

echo "Copying '$SSH_HOST' to '$SSH_DIR'"

cp ./ext/.htaccess ./dist
rsync -avz --delete -e ssh ./dist/ "$SSH_HOST":"$SSH_DIR"
