#!/usr/bin/env bash

# Deploy to ssh server
if [[ -z "$SSH_HOST" || -z "$SSH_DIR" || ! -d "./dist" ]]; then
    echo "Missing SSH_HOST ($SSH_HOST) or SSH_DIR ($SSH_DIR)."
    exit 1
fi

echo "Copying '$SSH_HOST' to '$SSH_DIR'"

cp ./ext/.htaccess ./dist
rsync -avz --delete -e ssh ./dist/ "$SSH_HOST":"$SSH_DIR"
